/**
 * Fetch announcements with ETag-friendly caching.
 *
 * The Worker serves `/announcements.json` (a static asset) with an
 * ETag generated by Cloudflare's asset pipeline. We send the last
 * ETag we saw via `If-None-Match` so the polling cadence is
 * essentially free on bandwidth — ~99 % of polls return 304.
 *
 * On 304 we return the cached payload from localStorage; on 200 we
 * cache the new body and the new ETag. On any error we return null
 * and the caller leaves the previous state alone.
 */

import {
  isAnnouncementsPayload,
  type AnnouncementsPayload,
} from './types';

const ETAG_KEY = 'inkmirror.announcements.etag';
const CACHE_KEY = 'inkmirror.announcements.cache';

interface CachedPayload {
  fetchedAt: string;
  payload: AnnouncementsPayload;
}

function readCache(): CachedPayload | null {
  try {
    const raw = localStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as Partial<CachedPayload>;
    if (
      typeof parsed.fetchedAt === 'string' &&
      isAnnouncementsPayload(parsed.payload)
    ) {
      return { fetchedAt: parsed.fetchedAt, payload: parsed.payload };
    }
    return null;
  } catch {
    return null;
  }
}

function writeCache(payload: AnnouncementsPayload, etag: string | null): void {
  try {
    localStorage.setItem(
      CACHE_KEY,
      JSON.stringify({ fetchedAt: new Date().toISOString(), payload }),
    );
    if (etag) localStorage.setItem(ETAG_KEY, etag);
    else localStorage.removeItem(ETAG_KEY);
  } catch {
    // Storage may be full / unavailable — fall through. The next poll
    // re-reads the live response anyway.
  }
}

function readEtag(): string | null {
  try {
    return localStorage.getItem(ETAG_KEY);
  } catch {
    return null;
  }
}

export interface FetchOptions {
  /** Override the URL — used for the preview path (?announcements=preview). */
  url?: string;
  /** Skip the ETag check (forces a fresh body). Used when previewing. */
  bypassEtag?: boolean;
}

/**
 * Fetch the announcements list. Returns:
 *   - payload + true when fresh content was retrieved (200)
 *   - cached payload + false when 304 hits (no change)
 *   - null on network/parse failure (caller keeps previous state)
 */
export async function fetchAnnouncements(
  options: FetchOptions = {},
): Promise<{ payload: AnnouncementsPayload; fresh: boolean } | null> {
  const url = options.url ?? '/announcements.json';
  const headers = new Headers({ accept: 'application/json' });
  if (!options.bypassEtag) {
    const lastEtag = readEtag();
    if (lastEtag) headers.set('if-none-match', lastEtag);
  }
  let res: Response;
  try {
    res = await fetch(url, { headers, credentials: 'omit' });
  } catch {
    return null;
  }

  if (res.status === 304) {
    const cached = readCache();
    if (cached) return { payload: cached.payload, fresh: false };
    // 304 with no cache shouldn't happen, but if it does, force a refetch
    // by clearing the etag and bailing — the next poll will get a 200.
    try { localStorage.removeItem(ETAG_KEY); } catch { /* ignore */ }
    return null;
  }

  if (!res.ok) return null;

  let parsed: unknown;
  try {
    parsed = await res.json();
  } catch {
    return null;
  }
  if (!isAnnouncementsPayload(parsed)) return null;

  const newEtag = res.headers.get('etag');
  if (!options.bypassEtag) writeCache(parsed, newEtag);
  return { payload: parsed, fresh: true };
}

/** Test-only / debug helper to clear the announcement cache. */
export function clearAnnouncementCache(): void {
  try {
    localStorage.removeItem(ETAG_KEY);
    localStorage.removeItem(CACHE_KEY);
  } catch {
    // ignore
  }
}
